$box = "ubuntu/bionic64"
$script = <<-SCRIPT
apt-get update

add-apt-repository ppa:redislabs/redis
apt-get update
apt-get install redis -y

mv /home/vagrant/redis.conf /etc/redis/
chown -R redis:redis /etc/redis
systemctl restart redis-server

ufw disable

SCRIPT

Vagrant.configure("2") do |config|

  (1..3).each do |i|

    config.vm.define "repl-#{i}" do |node|
      node.vm.box = $box
      node.vm.network "private_network", ip: "10.0.0.1#{i}"
      node.vm.hostname = "repl-#{i}"
      node.vm.provision "file", source: "./redis.conf", destination: "~/"
      node.vm.provision "shell", inline: $script
    end

    config.vm.define "master-#{i}" do |node|
      node.vm.box = $box
      node.vm.network "private_network", ip: "10.0.0.#{i}"
      node.vm.hostname = "master-#{i}"
      node.vm.provision "file", source: "./redis.conf", destination: "~/"
      node.vm.provision "shell", inline: $script
    end

  end

  config.vm.provider "virtualbox" do |v|
  	v.memory = 1024
  	v.cpus = 2
  end

end
